apiVersion: v1
kind: Namespace
metadata:
  name: local-storage
---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: local-operator-group
  namespace: local-storage
spec:
  targetNamespaces:
    - local-storage
---
apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
  name: redhat-local-storage-src
  namespace: openshift-marketplace
spec:
  type: appregistry
  endpoint: https://quay.io/cnr
  registryNamespace: hekumar
  displayName: "Red Hat Storage operators"
  publisher: "Red Hat Storage"
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: local-storage-operator
  namespace: local-storage
spec:
  channel: "4.3"
  installPlanApproval: Automatic
  name: local-storage-operator
  source: redhat-local-storage-src
  sourceNamespace: openshift-marketplace
